USE [master]
GO

/****** Object:  Database [GuardianLock]    Script Date: 1/25/2024 6:30:13 PM ******/
CREATE DATABASE [GuardianLock]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GuardianLock', FILENAME = N'C:\Users\asand\GuardianLock.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GuardianLock_log', FILENAME = N'C:\Users\asand\GuardianLock_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GuardianLock].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GuardianLock] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GuardianLock] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GuardianLock] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GuardianLock] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GuardianLock] SET ARITHABORT OFF 
GO

ALTER DATABASE [GuardianLock] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GuardianLock] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GuardianLock] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GuardianLock] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GuardianLock] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GuardianLock] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GuardianLock] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GuardianLock] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GuardianLock] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GuardianLock] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GuardianLock] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GuardianLock] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GuardianLock] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GuardianLock] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GuardianLock] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GuardianLock] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GuardianLock] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GuardianLock] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GuardianLock] SET  MULTI_USER 
GO

ALTER DATABASE [GuardianLock] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GuardianLock] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GuardianLock] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GuardianLock] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GuardianLock] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GuardianLock] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GuardianLock] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GuardianLock] SET  READ_WRITE 
GO

USE [GuardianLock]
GO

CREATE TABLE [Users] (
    UserID NVARCHAR(255) PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL,
    FirstName NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Salt NVARCHAR(MAX) NOT NULL,
    EncryptionKey NVARCHAR(MAX) NOT NULL
);

GO

CREATE TABLE [Files] (
    FileID INT PRIMARY KEY,
    FileName NVARCHAR(255) NOT NULL,
    FilePath NVARCHAR(MAX) NOT NULL,
    FileType NVARCHAR(50) NOT NULL,
    FileSize BIGINT NOT NULL,
    EncryptionStatus NVARCHAR(20) NOT NULL,
    OwnerID NVARCHAR(255) FOREIGN KEY REFERENCES [Users](UserID)
);

GO
